application/core/views.py
from flask import render_template, Blueprint, request, make_response, jsonify
from flask_login import login_required, current_user
from application.utils.article_scraper import text1
from werkzeug.utils import secure_filename
from flask import flash, request, redirect, url_for
from application.utils.file_uploader import allowed_file
from application import app, db
from application.utils.infections_sql import *
import pdfkit
import os

core = Blueprint('core', __name__)
config = pdfkit.configuration(wkhtmltopdf="D:\\pytek\\wkhtmltopdf\\bin\\wkhtmltopdf.exe")


@core.route('/', methods=['GET', 'POST'])
def index():
    count = int(request.cookies.get('visit-count', 0))
    count += 1
    count_number = 'You have visited this page ' + str(count) + ' times'

    resp = make_response(render_template('index.html', current_user=current_user, count_number=count_number))
    resp.set_cookie('visit-count', str(count))
    return resp


@core.route('/stats')
@login_required
def stats():
    return render_template('stats.html', current_user=current_user, number_result=number_result,
                           number_result1=number_result1,
                           number_result2=number_result2,
                           number_result3=number_result3,
                           number_result4=number_result4,
                           number_result5=number_result5,
                           number_result6=number_result6,
                           number_result7=number_result7,
                           number_result8=number_result8,
                           number_result9=number_result9,
                           number_result10=number_result10,
                           number_result11=number_result11,
                           number_result12=number_result12,
                           number_result13=number_result13,
                           number_result14=number_result14,
                           number_result15=number_result15,
                           number_result16=number_result16)


@core.route('/stats_file')
@login_required
def stats_file():
    return render_template('stats_file.html', current_user=current_user, number_result=number_result,
                           number_result1=number_result1,
                           number_result2=number_result2,
                           number_result3=number_result3,
                           number_result4=number_result4,
                           number_result5=number_result5,
                           number_result6=number_result6,
                           number_result7=number_result7,
                           number_result8=number_result8,
                           number_result9=number_result9,
                           number_result10=number_result10,
                           number_result11=number_result11,
                           number_result12=number_result12,
                           number_result13=number_result13,
                           number_result14=number_result14,
                           number_result15=number_result15,
                           number_result16=number_result16)


@core.route('/stats_file_pdf')
def stats_pdf():
    rendered = render_template('stats_file.html', current_user=current_user, number_result=number_result,
                               number_result1=number_result1,
                               number_result2=number_result2,
                               number_result3=number_result3,
                               number_result4=number_result4,
                               number_result5=number_result5,
                               number_result6=number_result6,
                               number_result7=number_result7,
                               number_result8=number_result8,
                               number_result9=number_result9,
                               number_result10=number_result10,
                               number_result11=number_result11,
                               number_result12=number_result12,
                               number_result13=number_result13,
                               number_result14=number_result14,
                               number_result15=number_result15,
                               number_result16=number_result16)
    pdf = pdfkit.from_string(rendered, False, configuration=config)

    response = make_response(pdf)
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = 'inline; filename=stats.pdf'

    return response


@core.route('/stats_json')
def stats_json():
    return jsonify(all=number_result,
                   ds=number_result1,
                   kp=number_result2,
                   lb=number_result3,
                   ls=number_result4,
                   ld=number_result5,
                   mp=number_result6,
                   mz=number_result7,
                   op=number_result8,
                   pk=number_result9,
                   pl=number_result10,
                   pm=number_result11,
                   sl=number_result12,
                   sk=number_result13,
                   wm=number_result14,
                   wp=number_result15,
                   zp=number_result16)


@core.route('/report', methods=['GET', 'POST'])
@login_required
def report():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        elif not allowed_file(file.filename):
            flash('Incorrect file extension, you should use .pdf, .doc or .docx')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            extension = filename.split()[-1]
            new_filename = "upload-{}_{}".format(current_user.account_id, extension)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], new_filename))
            flash('File updated successfully')
    return render_template('report.html', current_user=current_user)


@core.route('/actual_restrictions')
def actual_restrictions():
    return render_template('actual_restrictions.html', current_user=current_user, text1=text1)


@core.route('/ajax', methods=['POST'])
def ajax_request():
    username = request.form['username']
    return jsonify(username=username)

application/users/views.py
from flask import render_template, request, redirect, request, url_for, flash, abort, Blueprint
from flask_login import login_user, login_required, logout_user, current_user
from application.users.forms import LoginForm, RegistrationForm, UserInfoForm
from application.models import Account, UserInfo
from application import db

users = Blueprint('users', __name__)


@users.route('/personal-info', methods=['GET', 'POST'])
@login_required
def personal_info():
    form = UserInfoForm()
    if form.validate_on_submit():
        user_info = UserInfo(account_id=current_user.account_id,
                             first_name=form.first_name.data,
                             last_name=form.last_name.data,
                             voivodeship=form.voivodeship.data,
                             is_infected=form.is_infected.data)
        data_account_id = user_info.account_id
        data_first_name = user_info.first_name
        data_last_name = user_info.last_name
        data_voivodeship = user_info.voivodeship
        data_is_infected = user_info.is_infected
        if UserInfo.query.filter(UserInfo.account_id == current_user.account_id).first() is not None:
            db.engine.execute("DELETE FROM userinfo WHERE account_id = %s", data_account_id)
            db.engine.execute(
                "INSERT INTO userinfo(account_id, first_name, last_name, voivodeship, is_infected) VALUES(%s, %s, %s, %s, %s)",
                data_account_id, data_first_name, data_last_name, data_voivodeship, data_is_infected)
            db.session.commit()
            flash('Your personal information is updated now')
        else:
            db.engine.execute(
                "INSERT INTO userinfo(account_id, first_name, last_name, voivodeship, is_infected) VALUES(%s, %s, %s, %s, %s)",
                data_account_id, data_first_name, data_last_name, data_voivodeship, data_is_infected)
            db.session.commit()
            flash('Your personal information is saved now')
    return render_template('user_info.html', form=form)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = Account(email=form.email.data,
                       login=form.login.data,
                       password=form.password.data)
        data_login = user.login
        data_email = user.email
        data_password = user.password
        db.engine.execute("INSERT INTO accounts(login, email, password) VALUES(%s, %s, %s)", data_login, data_email,
                          data_password)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Account.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data):
            login_user(user)
            flash('Logged in successfully.')
            next = request.args.get('next')
            if next is None or not next[0] == '/':
                next = url_for('core.index')
            return redirect(next)
        else:
            flash("Wrong password.")
    return render_template('login.html', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You logged out.")
    return redirect(url_for('core.index'))

application/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field() }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <span style="color:red;">{{ error }}</span>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

application/templates/actual_restrictions.html
{% extends "base.html" %}

{% block title %} Actual restrictions {% endblock title %}

{% block content %}

<div class="jumbotron mt-2 text-left">
    {% autoescape false %}
        <p>{{ text1[0] }}
    {% endautoescape %}
</div>

{% endblock content %}

application/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- CSS -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}">
    <!-- custom css -->
    <link id="pagestyle" rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <!-- Font: Lato -->
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='assets/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='assets/favicon-16x16.png') }}">

    <meta charset="UTF-8">
    <title> COVID-19 APP {% block title %} {% endblock title %}</title>

</head>

<body>

<!-- TODO przycisk z nazwa usera nie klika sie na calym polu, przez ikony. -->
    <div class="header">
        <a href="{{ url_for('core.index') }}" class="logo">C<i class="fas fa-virus"></i>VID-19 APP</a>
        {% if current_user.is_authenticated %}
            <div class="header-right">
                <a href="{{ url_for('core.index') }}">Home</a>
                <a href="{{ url_for('core.report') }}">Report</a>
                <a href="{{ url_for('core.stats') }}">Statistics</a>
                <div class="dropdown-wrapper">
                    <button class="dropbtn" onclick="userMenuDropdown()">
                        <i class="far fa-user-circle" style="font-size:22px;"></i>
                        {{ current_user.login }}
                        <i class="fa fa-caret-down" style="font-size:16px;"></i>
                    </button>
                    <div class="dropdown-content" id="user-dropdown">
                        <a href="{{ url_for('users.personal_info') }}">Personal information</a>
                        <a href="{{ url_for('users.logout') }}">Log out</a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="header-right">
                <a href="/">Home</a>
                <a href="/login">Log in</a>
                <a href="/register">Sign up</a>
            </div>
        {% endif %}
    </div>

    <!-- Page content -->
    <div class="container">

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for mesg in messages %}
                <p class="dotted">{{ mesg }}</p>
            {% endfor %}
       {% endif %}
    {% endwith %}
<br>


    {% block content %}

    {% endblock content %}
    </div>


    <!-- SCRIPTS -->
    <!-- FontAwesome -->
    <script src="https://kit.fontawesome.com/ba76e96f76.js" crossorigin="anonymous"></script>
    <!-- JQuery -->
    <script src="{{ url_for('static', filename='js/vendor/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ url_for('static', filename='js/vendor/bootstrap.bundle.min.js') }}"></script>
    <!-- main.js script -->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>


</body>

<footer>
<button type="button" class="btn btn-dark btn-sm" onclick="swapStyleSheet('{{ url_for('static', filename='css/dark.css') }}')">Dark Style</button>
<button type="button" class="btn btn-light btn-sm" onclick="swapStyleSheet('{{ url_for('static', filename='css/main.css') }}')">Classic Style</button>


</footer>

</html>

application/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron mt-2 text-center">
<h1>COVID-19 APP</h1>
<h2>
    COVID-19 APP is simple web application, where you can check actual restrictions, check statistics for whole world or
    registered users. You have also possibility to upload your form for infected people, which is meant to be send to
    your WSSE.
</h2>

<hr class="my-4">
<a class="btn btn-primary btn-lg" href="{{ url_for('core.actual_restrictions') }}" role="button">Check actual restrictions</a>

    <br>

<small>{{ count_number }}</small>
<br>
<br>
<h1>In which category for vaccine will you be?</h1>
    <br>
<form action="" method="POST">
    <h5>How old are you?</h5>
<input type="number" name="age" id="age">
    <br>
<input class="form-check-input" type="checkbox" value="1" id="swh">
<label class="form-check-label" for="swh">
    Do you live in social welfare home?
</label>
    <br>
<input class="form-check-input" type="checkbox" value="1" id="gov">
<label class="form-check-label" for="gov">
    Are you government worker (teacher, police officer, firefighter etc.)?
</label>
    <br>
<input class="form-check-input" type="checkbox" value="1" id="sick">
<label class="form-check-label" for="sick">
    Are you chronically ill, undergoing treatment or diagnosis?
</label>
    <br>
<input type="button" value="Submit" onclick="return loadXMLDoc()">
</form>
    <h3>Your category is:</h3>
<div class="result" id="myDiv"></div>

</div>

{% endblock content %}

application/templates/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock title %}

{% block content %}

    <div class="jumbotron mt-2 text-center">
        <h1>Sign in</h1>
        <br>

{% from "_formhelpers.html" import render_field %}
<form method="post">
    {{ form.hidden_tag() }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    {{ form.submit() }}

</form>

    </div>

{% endblock content %}

application/templates/register.html
{% extends "base.html" %}

{% block title %} Register {% endblock title %}

{% block content %}

    <div class="jumbotron mt-2 text-center">
        <h1>Sign up</h1>
        <br>

{% from "_formhelpers.html" import render_field %}
<form method="post">
    {{ form.hidden_tag() }}
    {{ render_field(form.email) }}<br>
    {{ render_field(form.login) }}<br>
    {{ render_field(form.password) }}<br>
    {{ render_field(form.pass_confirm) }}<br>
    {{ form.submit() }}

</form>

    </div>

{% endblock content %}

application/templates/report.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron mt-2 text-center">
    <h1>Report your situation</h1>
    <h2>Upload your form for infected persons (to be sent to yours WSSE)</h2>
    <p>The file must have .pdf, .doc, .docx or .odt extension</p>
    <form method=post enctype=multipart/form-data>
      <input type=file name=file accept=".pdf,.doc,.docx,.odt">
      <input type=submit value=Upload>
    </form>
</div>

{% endblock content %}

application/templates/stats.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron mt-2 text-center">
    <h1>Stats</h1>
<iframe src="https://ourworldindata.org/grapher/total-cases-covid-19?tab=map" width="100%" height="600px" marginheight="100px"></iframe>
    <br>
<h2>Show number of infected people from this website</h2>
<p>Actual number of infected people is: {{ number_result }}</p>
<p>Data for every voivodeship: Lower Silesian {{ number_result1 }}, Kuyavian-Pomeranian {{ number_result2 }},
Lublin {{ number_result3 }}, Lubusz {{ number_result4 }}, Łódź {{ number_result5 }},
Lesser Poland {{ number_result6 }}, Masovian {{ number_result7 }}, Opole {{ number_result8 }},
Subcarpathian {{ number_result9 }}, Podlaskie {{ number_result10 }}, Pomeranian {{ number_result11 }},
Silesian {{ number_result12 }}, Holy Cross {{ number_result13 }}, Warmian-Masurian {{ number_result14 }},
Greater Poland {{ number_result15 }}, West Pomeranian {{ number_result16 }}</p>
<br>
<h3>Get this statistics in:</h3>
<a class="btn btn-outline-info" href="{{ url_for('core.stats_pdf') }}" role="button">PDF</a>
<a class="btn btn-outline-info" href="{{ url_for('core.stats_json') }}" role="button">JSON</a>
<a class="btn btn-outline-info" href="{{ url_for('core.stats_file') }}" role="button">HTML</a>

</div>


{% endblock content %}

application/templates/stats_file.html
<div class="jumbotron mt-2 text-center">
    <h1>Stats</h1>
<p>Actual number of infected people is: {{ number_result }}</p>
<p>Data for every voivodeship: Lower Silesian {{ number_result1 }}, Kuyavian-Pomeranian {{ number_result2 }},
Lublin {{ number_result3 }}, Lubusz {{ number_result4 }}, Lodz {{ number_result5 }},
Lesser Poland {{ number_result6 }}, Masovian {{ number_result7 }}, Opole {{ number_result8 }},
Subcarpathian {{ number_result9 }}, Podlaskie {{ number_result10 }}, Pomeranian {{ number_result11 }},
Silesian {{ number_result12 }}, Holy Cross {{ number_result13 }}, Warmian-Masurian {{ number_result14 }},
Greater Poland {{ number_result15 }}, West Pomeranian {{ number_result16 }}</p>

</div>

application/templates/user_info.html
{% extends "base.html" %}

{% block title %} Personal information {% endblock title %}

{% block content %}

    <div class="jumbotron mt-2 text-center">
        <h1>User information</h1>
        <p>Add or update your personal data</p>
    {% from "_formhelpers.html" import render_field %}
<form method="post">
    {{ form.hidden_tag() }}
    {{ render_field(form.first_name) }}<br>
    {{ render_field(form.last_name) }}<br>
    {{ render_field(form.voivodeship) }}<br>
    {{ render_field(form.is_infected) }}<br>
    {{ form.submit() }}

</form>
    </div>

{% endblock content %}

application/templates/welcome.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron mt-2 text-center">
    <h1>welcome</h1>
</div>

{% endblock content %}
<!-- user info TODO -->